### ISSUE TITLE
Unable to download Images

### ISSUE THREAD

**Issue by Vitexus** [burtyb/clusterhat-image#9]
```
root@canby:/var/tmp# wget https://dist1.8086.net/clusterctrl/usbboot/bullseye/2023-05-03/2023-05-03-4-bullseye-ClusterCTRL-arm64-lite-usbboot.tar.xz
--2023-07-01 14:30:11--  https://dist1.8086.net/clusterctrl/usbboot/bullseye/2023-05-03/2023-05-03-4-bullseye-ClusterCTRL-arm64-lite-usbboot.tar.xz
Resolving dist1.8086.net (dist1.8086.net)... 95.216.250.64
Connecting to dist1.8086.net (dist1.8086.net)|95.216.250.64|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-01 14:30:12 ERROR 403: Forbidden.
```

Please fix permissions.

**Comment by burtyb** [comment]
Thanks, should be fixed now.

**Comment by Vitexus** [comment]
My Packaged fork https://github.com/PureHTML/clusterhat-image of your tools is still not production ready and the PIs looking forward for its fresh system.

Thank you very much!

![1688243850953](https://github.com/burtyb/clusterhat-image/assets/2621130/4e0c81b7-6868-4d65-82a9-b92c31e6f05a)
